[project]
name = "epub-metadata-extractor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ollama>=0.6.0",
    "outlines>=1.2.5",
    "pydantic-ai>=1.0.10",
    "tika>=3.1.0",
]
